version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar/x23420065:sonartokenKEY
    HOST: prod/sonar/x23420065:HOST
    Organization: prod/sonar/x23420065:Organization
    Project: prod/sonar/x23420065:Project
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      
  pre_build:
    commands:
      - python --version
      - python manage.py collectstatic --noinput  
      - echo "PyLint Started"
      - pylint notessharing/**/*.py || true
      - echo "pre build stage completed - PyLint Completed!!"      

  build:
    commands:
      - echo "Testing Stage"
artifacts:
  files:
    - '**/*'
